const ACTION = {
    CHANGE: "CHANGE",
    START: "START",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    RESET_ACTION: "RESET_ACTION",
    SET_DATA: "SET_DATA",
    REFETCH: "REFETCH",
    RESET_STATE: "RESET_STATE",
    RESET_LIST: "RESET_LIST"
}

export { ACTION }